# Generated by Django 4.2.3 on 2023-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('character', models.CharField(max_length=20)),
                ('dialogue', models.CharField(max_length=1000)),
                ('dialogue_number', models.IntegerField()),
                ('place', models.CharField(max_length=255, null=True)),
                ('uploaded_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
