# Generated by Django 4.2.3 on 2023-07-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_and_Search', '0002_fileupload_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogue',
            old_name='uploaded_date',
            new_name='created_date',
        ),
    ]
