# Generated by Django 4.2.3 on 2023-07-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_and_Search', '0004_fileupload_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=32)),
            ],
        ),
    ]
