# Generated by Django 4.2.3 on 2023-07-23 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Register_and_Search', '0005_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='filepath',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='character',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='character',
            field=models.CharField(max_length=255),
        ),
    ]
