# Generated by Django 4.2.3 on 2023-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_and_Search', '0006_dialogue_filepath_alter_character_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_file',
            field=models.FileField(upload_to=''),
        ),
    ]
